### ISSUE TITLE
Align GO and Monarch json-ld contexts

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#582]
TODO: report on clashes

**Comment by cmungall** [comment]
* CGD Was=http://identifiers.org/cgd/ [registry/go_context.jsonld], Now=http://ohsu.edu/cgd/ [registry/monarch_context.jsonld]
 * EC Was=http://www.expasy.org/enzyme/ [registry/go_context.jsonld], Now=http://identifiers.org/ec-code/ [registry/monarch_context.jsonld]
 * GO_REF Was=http://purl.obolibrary.org/obo/go/references/ [registry/go_context.jsonld], Now=http://www.geneontology.org/cgi-bin/references.cgi#GO_REF: [registry/monarch_context.jsonld]
 * GenBank Was=http://www.ncbi.nlm.nih.gov/entrez/viewer.fcgi?db=nucleotide&val= [registry/go_context.jsonld], Now=http://www.ncbi.nlm.nih.gov/nuccore/ [registry/monarch_context.jsonld]
 * HGNC Was=http://identifiers.org/hgnc/ [registry/go_context.jsonld], Now=http://identifiers.org/hgnc/HGNC: [registry/monarch_context.jsonld]
 * MGI Was=http://identifiers.org/mgi/ [registry/go_context.jsonld], Now=http://www.informatics.jax.org/accession/MGI: [registry/monarch_context.jsonld]
 * NCBIGene Was=http://identifiers.org/ncbigene/ [registry/go_context.jsonld], Now=http://www.ncbi.nlm.nih.gov/gene/ [registry/monarch_context.jsonld]
 * OMIM Was=http://omim.org/entry/ [registry/go_context.jsonld], Now=http://purl.obolibrary.org/obo/OMIM_ [registry/monarch_context.jsonld]
 * PAINT_REF Was=http://www.pantherdb.org/panther/lookupId.jsp?id=PTHR [registry/go_context.jsonld], Now=http://www.geneontology.org/gene-associations/submission/paint/ [registry/monarch_context.jsonld]
 * PANTHER Was=http://identifiers.org/panther.family/ [registry/go_context.jsonld], Now=http://www.pantherdb.org/panther/family.do?clsAccession= [registry/monarch_context.jsonld]
 * PDB Was=http://www.rcsb.org/pdb/cgi/explore.cgi?pdbId= [registry/go_context.jsonld], Now=http://identifiers.org/PDB: [registry/monarch_context.jsonld]
 * PMCID Was=http://www.ncbi.nlm.nih.gov/sites/entrez?db=pmc&cmd=search&term= [registry/go_context.jsonld], Now=http://www.ncbi.nlm.nih.gov/pmc/ [registry/monarch_context.jsonld]
 * PomBase Was=http://identifiers.org/pombase/ [registry/go_context.jsonld], Now=http://identifiers.org/PomBase: [registry/monarch_context.jsonld]
 * RGD Was=http://identifiers.org/rgd/ [registry/go_context.jsonld], Now=http://rgd.mcw.edu/rgdweb/report/gene/main.html?id= [registry/monarch_context.jsonld]
 * RefSeq Was=http://www.ncbi.nlm.nih.gov/entrez/viewer.fcgi?val= [registry/go_context.jsonld], Now=http://www.ncbi.nlm.nih.gov/refseq/?term= [registry/monarch_context.jsonld]
 * TAIR Was=http://identifiers.org/tair.locus/ [registry/go_context.jsonld], Now=http://identifiers.org/TAIR: [registry/monarch_context.jsonld]
 * ZFIN Was=http://identifiers.org/zfin/ [registry/go_context.jsonld], Now=http://zfin.org/ [registry/monarch_context.jsonld]
 * dbSNP Was=http://identifiers.org/dbsnp/ [registry/go_context.jsonld], Now=http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs= [registry/monarch_context.jsonld]
 * dictyBase Was=http://identifiers.org/dictybase/ [registry/go_context.jsonld], Now=http://dictybase.org/gene/ [registry/monarch_context.jsonld]

**Comment by TomConlin** [comment]
1) I applaud giving the primary database URLs their due.
2) dipper warns on non 1:1 maps  https://github.com/monarch-initiative/dipper/blob/master/dipper/utils/CurieUtil.py#L21  GO might want to as well
3) mind httpS where possible

**Comment by cmungall** [comment]
> I applaud giving the primary database URLs their due
The problem here is that these are often ad-hoc and subset to change. In GO we are going for identifiers.org, more stable, predictable

> dipper warns on non 1:1 maps https://github.com/monarch-initiative/dipper/blob/master/dipper/utils/CurieUtil.py#L21 GO might want to as well

We should look at merging dipper CurieUtil and https://github.com/prefixcommons/prefixcommons-py

> mind httpS where possible

I have gotten assurances from identifiers.org that they will support http in perpetuity. Same of course true for OBO. Stability is key here

**Comment by cmungall** [comment]
Note the list above only includes cases where the prefix matches or the URL matches.

It isn't reporting the fact that GO has

```
- database: Reactome
  name: Reactome - a curated knowledgebase of biological pathways
  synonyms:
    - REACTOME
    - REAC
  rdf_uri_prefix: http://identifiers.org/reactome/
  generic_urls:
    - http://www.reactome.org/
  entity_types:
    - type_name: entity
      type_id: BET:0000000
      id_syntax: R-[A-Z]{3}-[0-9]+(-[0-9]+){0,1}(\.[0-9]+){0,1}
      url_syntax: http://www.reactome.org/content/detail/[example_id]
      example_id: Reactome:R-HSA-109582
      example_url: http://www.reactome.org/content/detail/R-HSA-109582
```

whereas dipper has 

```
'REACT': 'http://www.reactome.org/PathwayBrowser/#/'
```

It looks like we have just recommended REACT to translator folks ah well. I'm not sure where this abbreviation came from.

But the URL is a good example of a bad semantic web PURL `http://www.reactome.org/PathwayBrowser/#/`
